/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-06 06:42:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/springwork/finalPro/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1672981764611L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/header.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- js -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.1.min.js\" integrity=\"sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css\"/>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 폰트 -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@200;300;400;500;600;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"wrap\">\r\n");
      out.write("        <div id=\"header\">            \r\n");
      out.write("            <div class=\"header\">\r\n");
      out.write("                <div class=\"header-top\">\r\n");
      out.write("                    <div class=\"user-info\">\r\n");
      out.write("                        <ul class=\"user\">\r\n");
      out.write("                            <li><a href=\"#\">장바구니</a></li>\r\n");
      out.write("                            <li><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("                            <li><a href=\"#\">로그인</a></li>\r\n");
      out.write("                            <li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>                \r\n");
      out.write("                <div class=\"header-mid\">\r\n");
      out.write("                    <div class=\"mid-f\">\r\n");
      out.write("                        <h1>\r\n");
      out.write("                            <a href=\"#\">樂受文化</a>\r\n");
      out.write("                        </h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mid-m\">\r\n");
      out.write("                        <div class=\"category\">\r\n");
      out.write("                            <ul class=\"nav_category\">\r\n");
      out.write("                                <li><a href=\"\">수강안내</a></li>\r\n");
      out.write("                                <li><a href=\"\">시설안내</a></li>\r\n");
      out.write("                                <li><a href=\"\">커뮤니티</a></li>\r\n");
      out.write("                                <li><a href=\"\">고객센터</a></li>                            \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>                    \r\n");
      out.write("                    <div class=\"mid-b\">\r\n");
      out.write("                        <div class=\"button_box\">\r\n");
      out.write("                            <div class=\"button_img\">                            \r\n");
      out.write("                                <button type=\"button\"><img src=\"resources/img/icons8-달력-32.png\" alt=\"달력\"></button>\r\n");
      out.write("                                <button type=\"button\"><img src=\"resources/img/icons8-하트-50.png\" alt=\"찜\"></button>\r\n");
      out.write("                                <button type=\"button\" class=\"main_btn\"><img src=\"resources/img/icons8-수색-30.png\" alt=\"검색\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav_bar\">\r\n");
      out.write("                    <div class=\"inner\">\r\n");
      out.write("                        <div class=\"nav_info\">\r\n");
      out.write("                            <h4>강좌안내</h4>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"\">수강신청</a></li>\r\n");
      out.write("                                <li><a href=\"\">강좌목록</a></li>\r\n");
      out.write("                                <li><a href=\"\">강좌스케줄</a></li>\r\n");
      out.write("                                <li><a href=\"\">신청방법</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"nav_info\">\r\n");
      out.write("                            <h4>시설안내</h4>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"\">개요 및 시설</a></li>\r\n");
      out.write("                                <li><a href=\"\">시설현황</a></li>\r\n");
      out.write("                                <li><a href=\"\">이용안내</a></li>\r\n");
      out.write("                                <li><a href=\"\">오시는 길</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"nav_info\">\r\n");
      out.write("                            <h4>커뮤니티</h4>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"\">공지사항/이벤트</a></li>\r\n");
      out.write("                                <li><a href=\"\">모임게시판</a></li>\r\n");
      out.write("                                <li><a href=\"\">수강생 후기</a></li>\r\n");
      out.write("                                \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"nav_info\">\r\n");
      out.write("                            <h4>고객센터</h4>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"\">1:1문의</a></li>\r\n");
      out.write("                                <li><a href=\"\">자주하는문의</a></li>                                \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("                <form action=\"\" method=\"\" class=\"h_form\">\r\n");
      out.write("                    <div class=\"search_hide\">\r\n");
      out.write("                        <div class=\"search_bar\">\r\n");
      out.write("                            <div class=\"search_array\">\r\n");
      out.write("                                <div class=\"search_select\">\r\n");
      out.write("                                    <select name=\"\" id=\"\">\r\n");
      out.write("                                        <option value=\"0\">전체검색</option>\r\n");
      out.write("                                        <option value=\"강좌\">강좌</option>\r\n");
      out.write("                                        <option value=\"시설\">시설</option>\r\n");
      out.write("                                        <option value=\"커뮤니티\">커뮤니티</option>                                    \r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>                        \r\n");
      out.write("                                <div class=\"search_inp\">\r\n");
      out.write("                                    <input type=\"text\" id=\"\" name=\"\">\r\n");
      out.write("                                    <button type=\"submit\"><img src=\"resources/img/icons8-수색-30.png\" alt=\"찾기\"></button>\r\n");
      out.write("                                    <button type=\"button\" class=\"search_cancle\"><img src=\"resources/img/icons8-지우다-24.png\" alt=\"취소\"></button>\r\n");
      out.write("                                    <input type=\"hidden\">\r\n");
      out.write("                                </div>       \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>    \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>            \r\n");
      out.write(" </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // 검색 버튼 fade\r\n");
      out.write("        $(function() {\r\n");
      out.write("            $('.main_btn').on('click', function(e) {\r\n");
      out.write("                $('.h_form').fadeIn(300)\r\n");
      out.write("                \r\n");
      out.write("                $('.search_cancle').on('click', function() {\r\n");
      out.write("                    $('.h_form').fadeOut(300)\r\n");
      out.write("                })\r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        // 헤더 카데고리 바 숨겨진 div\r\n");
      out.write("        $(function() {\r\n");
      out.write("            $('.nav_category').mouseover(function() {\r\n");
      out.write("                $('.nav_bar').stop().fadeIn(1);\r\n");
      out.write("            })\r\n");
      out.write("            $($('.nav_bar')).mouseleave(function() {\r\n");
      out.write("                $(this).fadeOut(1);\r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
